apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue  # switch the cloure in here
  ports:
  - port: 80
    targetPort: 80
  type: NodePort

