apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: PLACEHOLDER
  template:
    metadata:
      labels:
        app: myapp
        version: PLACEHOLDER
    spec:
      containers:
      - name: myapp
        image: gcr.io/primeval-mark-378114/myapp:latest
        ports:
        - containerPort: 3000

