apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    metadata:
      labels:
        version: eks
    spec:
      containers:
        - name: myapp
          image: 065217600364.dkr.ecr.eu-north-1.amazonaws.com/myapp:latest
  selector:
    matchLabels:
      version: eks

