name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: myapp
  GCP_PROJECT_ID: primeval-mark-378114
  GCR_REGISTRY: gcr.io
  AWS_REGION: eu-north-1
  AWS_ECR_REGISTRY: 891376976638.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker ${{ env.GCR_REGISTRY }}

    - name: Authenticate to AWS by cridentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::891376976638:role/github-actions-oidc-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY

    - name: Build Docker image
      run: |
        docker build -t $GCR_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME:latest .
        docker tag $GCR_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME:latest $AWS_ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Push to GCR and ECR
      run: |
        docker push $GCR_REGISTRY/$GCP_PROJECT_ID/$IMAGE_NAME:latest
        docker push $AWS_ECR_REGISTRY/$IMAGE_NAME:latest

